### ISSUE TITLE
Datasets used for leaderboard

### ISSUE THREAD

**Issue by jvrsgsty** [bethgelab/robust-vision-benchmark#11]
I know it seems that the RBV is no longer active, but I was curious what datasets were used to generate the leaderboard. Is it just the images on the `data/` directory in this repo or was this run using some bigger datasets? 

Generating adversarial examples for our model using foolbox takes a while (almost a minute per example) on our local setup with Titan X cards.

**Comment by jonasrauber** [comment]
If I am not mistaken, it was done on the data in the `data` folder, yes.

P.S. I wouldn't consider one minute per example (on a single GPU) long; depending on the model, dataset and attacks, creating adversarials can be one or two orders of magnitude more costly (e.g. hours/sample).
