### ISSUE TITLE
what if you have some technique not incorporated into the model?

### ISSUE THREAD

**Issue by kirk86** [bethgelab/robust-vision-benchmark#4]
Hi everyone. Thank you for making this possible. I was wondering if it is possible to submit some models which actually do not incorporate the defense mechanism inside the model? What I mean by that, is for instance, we have a model `x` trained normally on one of the available datasets and then we have a defense mechanism `y` which is not incorporated into `x`. To give a diagram of such a system `z->y->x`. Assuming we have an input `z` which could be either attacked or not. We don't know. We pass that input through 'y', i.e. `z1 = y(z)`. `z1` is the output of the defense mechanism and then we feed that into `x`, i.e. `z2 = x(z1)` to get our final predictions. We could incorporate `y` into `x` but due to time constraints we want to get a rough idea of how this defense stands in the benchmark. How could we submit such as model. Is that possible? A minimal working example would be really helpful. 
Thank you!

**Comment by wielandbrendel** [comment]
Hi @kirk86, I am happy to hear that you aim to submit your model to the benchmark. Your use case sounds quite simple. As you say the only thing you need to do is to treat y(z) is a preprocessing to your model and combine them as such (i.e. z -> x(y(z))). A minimal working example is difficult as it depends what your preprocessing function y(.) and your model x(.) is, but in principle that sounds super straight forward. The benchmark expects a single model which gets an input and returns one output (anything else would be completely infeasible).

**Comment by kirk86** [comment]
@wielandbrendel thanks for your prompt response I'll try to play a little bit by submitting only the `x` part and if that works I'll try to change the code a little bit to look more like what the system is expecting `x(y(z))`. I have one question thought since I am not super familiar with docker. Is it possible to specify external libraries to be installed in your docker file? for instance do you have to write in your dockerfile `RUN pip3 install pytorch` or could something like this `RUN conda install pytorch` would also work?
