### ISSUE TITLE
bson version issue

### ISSUE THREAD

**Issue by xmodar** [bethgelab/robust-vision-benchmark#6]
After running `rvb-test-model`, I get the following error.

```
##### CONNECTING TO THE RUNNING SERVER ######
Server version 0.9.1
Performing basic checks for the code.
Traceback (most recent call last):
  File "/home/modar/miniconda3/bin/rvb-test-model", line 208, in <module>
    test_model(args.directory, no_cache=args.no_cache)
  File "/home/modar/miniconda3/bin/rvb-test-model", line 107, in test_model
    p, g = model.predictions_and_gradient(image, label)
  File "/home/modar/miniconda3/lib/python3.6/site-packages/robust_vision_benchmark/client.py", line 186, in predictions_and_gradient
    result = self._post('/predictions_and_gradient', data)
  File "/home/modar/miniconda3/lib/python3.6/site-packages/robust_vision_benchmark/client.py", line 276, in _post
    data = bson.dumps(data)
AttributeError: module 'bson' has no attribute 'dumps'
```

It turned out that there is a new version (0.5.1) of `bson` that doen't implement the `dumps` function. All what you need to do to fix this, is to specify which version of `bson` you want to be installed in your docker file.

```
# install required packages
RUN pip3 install --no-cache-dir bson==0.4.6
RUN pip3 install --no-cache-dir foolbox
RUN pip3 install --no-cache-dir robust_vision_benchmark
```

**Comment by jonasrauber** [comment]
Hi @ModarTensai, you already closed this issue but I wanted to add: the latest `bson` version still has a dumps function, so that cannot be the problem (see e.g. the README at https://github.com/py-bson/bson)

**Comment by xmodar** [comment]
Thanks @jonasrauber, you are right, my bad. The problem is explained here ([https://github.com/py-bson/bson/issues/69](https://github.com/py-bson/bson/issues/69)). After installing `pymongo` it overrides the `bson` installation you have. So, reinstalling `bson` after `pymongo` fixes the issue.
