### ISSUE TITLE
question for leaderboard model structure

### ISSUE THREAD

**Issue by ZekunStevenZhang** [bethgelab/robust-vision-benchmark#7]
Thanks for posting this benchmark and showing the leaderboard results. I got a question for the structure of the model tested in leaderboard part.
As shown in the leaderboard webpage, the cifar dataset and mnist dataset both have a model called **"simple_cnn"**.  Could u plz tell the specific structure of this model or give me a reference link for the code of this model? Thanks, that would be really helpful to me.

**Comment by wielandbrendel** [comment]
We used the standard Keras models:
- https://github.com/keras-team/keras/blob/master/examples/cifar10_cnn.py
- https://github.com/keras-team/keras/blob/master/examples/mnist_cnn.py

**Comment by ZekunStevenZhang** [comment]
got it, thanks
