### ISSUE TITLE
Feature: Show attack success rate for totals

### ISSUE THREAD

**Issue by Spenhouet** [bethgelab/robust-vision-benchmark#8]
Currently the attack success rate is only shown and visualized for the model-attack results.

I propose that additionally the total attack success rate is shown and visualized.

**Comment by jonasrauber** [comment]
Maybe, but actually strong unbounded attacks should succeed almost always anyway and it's not really the focus here. The Robust Vision Benchmark is somewhat outdated and I don't plan to make such extensions at the moment. Rather, a complete makeover would be necessary, but that's not on the agenda right now.

**Comment by Spenhouet** [comment]
Okay, thanks for the reply. The benchmark seemed like an active project / competition to me. The website prominently shows that new submissions are welcome and there are currently not many submissions. Sad to hear that this project is not kept up to date. Looked good and unique to me.

**Comment by jonasrauber** [comment]
I'd love to keep it alive, but there have never really been submissions and some of our original decisions and choices were suboptimal. Right now it's not the way I want it to be but other projects have higher priority.

**Comment by jonasrauber** [comment]
P.S. the RVB was somewhat superseeded by our NeurIPS 2018 Adversarial Vision Challenge: https://www.crowdai.org/challenges/adversarial-vision-challenge
