### ISSUE TITLE
"Total score" is actually an "average score"?

### ISSUE THREAD

**Issue by Spenhouet** [bethgelab/robust-vision-benchmark#9]
> The total score of an attack is just the average of the corresponding model-attack-pair scores.

Not to be nitpicking but wouldn't the "total score" be the sum?

It actually seems to be the "average score". Maybe also call it that? Or else this is just confusing.

**Comment by jonasrauber** [comment]
_Total score_ in the sense of _overall score_ over all models, not committing or referring to a particular way of calculation. For models, the _total score_ is acutally completely different from both average and sum.
